title: &nbsp;&nbsp;Yimin Guo # your name (or website title) here
logo: "/images/yiminguo-min-2.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Pursuing Master in Economics at University of Wsiconsin-Madison
  <br><br>
  Seeking opportunities in data analytics and data science 
  <br><br>
  <a href="https://www.linkedin.com/in/guo-yimin/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
